### ISSUE TITLE
Average load based on core count instead of lucky number

### ISSUE THREAD

**Issue by steffenmandrup** [codius/codiusd#107]
As a default the os.loadavg() showcases values based on cores. Therefore a 1.0 equals 100% utilization based on a single core system. In a dual core system 2.0 would be the same and 4.0 in a quad core system and so forth. So in a single core system 1.0 would be bad but in a quad core system it would be nothing.

Running a multi-core setup this would however make the server look overused and make developers choose another host eventhough there was a lot of processing power left. They have to have a way to know what number is the max to get an idea of the utilization of the system ressources.

I suggest that the averageload is changed to os.loadavg() / core count to give a more valid representation or atleast as a minimum add information about the core count in /info

**Comment by traviscrist** [comment]
Added in PR #108 closing.
