### ISSUE TITLE
request: allow contract version checking

### ISSUE THREAD

**Issue by kruisdraad** [codius/codiusd#126]
With the coming of 1.2.1 and enforcement of a functional host before running it, it would be great if you have a mechanism that checks a version before allowing the contract to be deployed. For example some kind if minimal version that is required listed in the manifest.

This will prevent system owners to stay at an older version then the contract owner would prefer.

**Comment by SneakyFish5** [comment]
Is this what you mean? https://github.com/codius/codius/issues/62

**Comment by kruisdraad** [comment]
yeah sorry, they are the same
