### ISSUE TITLE
Peerfinder / peers is not working correctly with 1.2.3

### ISSUE THREAD

**Issue by mkimid** [codius/codiusd#134]
Need to add one line as 

  this.config.selfTestSuccess = this.wsSuccess && this.uploadSuccess && this.httpSuccess

at line number 129 of SelfTest.ts

**Comment by njlie** [comment]
Fixed in #135, released in version 1.2.4. Thanks for catching this.

**Comment by mkimid** [comment]
IMO, there is two points are affected 

peers.ts  - line #20 

if (!config.selfTestSuccess) {
      throw Boom.forbidden('This host is misconfigured.')
}
