### ISSUE TITLE
Feature Request: Show public host statistics

### ISSUE THREAD

**Issue by justmoon** [codius/codiusd#27]
It would be very useful if each host reported basic stats like the number of running contracts.

**Comment by adrianhopebailie** [comment]
PROPOSAL

 - Bind `GET /pods` to `PodDatabase.getRunningPods()`
 - Bind `GET /` to a static `index.html` which populates a list of running pods by fetching `/pods`

**Comment by PW2512** [comment]
Very interested in this as currently I’m unsure of a way we can monitor/log/display any running contracts

**Comment by justmoon** [comment]
Question is whether it's a good idea to make this information public. On one hand, URLs shouldn't be considered private. On the other hand, this feature definitely makes an attacker's life a lot easier to scan for vulnerable contracts. Or if you are trying to DoS a certain contract, you can use this to chase it.

Independent of that, I like the idea of providing an index.html with some useful information like whether the host is full etc.

@PW2512 The host can see contracts running on their host with `hyperctl list`.

**Comment by lazmo88** [comment]
@justmoon: Independent of that, I like the idea of providing an index.html with some useful information like whether the host is full etc.

How about just displaying available pod "slots" vs "slots" occupied without any sensitive information about the pods itself? 🤔

**Comment by andywong418** [comment]
Closed in pull request #50 and #39

**Comment by andywong418** [comment]
Closed in pull request #50 and #39
