### ISSUE TITLE
Unhandled promise rejection in logs

### ISSUE THREAD

**Issue by davidmckenzie** [codius/codiusd#31]
```
Jun  7 03:52:14 codiusd[4286]: (node:4314) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 34): Error: getaddrinfo ENOTFOUND codius.example.com codius.example.com:443
Jun  7 03:52:23 codiusd[4286]: (node:4314) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 39): Error: getaddrinfo ENOTFOUND codius.example.com codius.example.com:443
Jun  7 03:52:38 codiusd[4286]: (node:4314) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 47): Error: getaddrinfo ENOTFOUND codius.example.com codius.example.com:443
```
Seems to be due to a misconfigured node attempting to peer?

**Comment by adrianhopebailie** [comment]
This looks like the host is attempting to connect to `codius.example.com`.
Is this configured in the host config anywhere?

Check in `/etc/systemd/system/codiusd.service`
Also run `uname -n` and ensure it does NOT return `codius.example.com`

**Comment by spearl** [comment]
If this is still happening, please re-open. But since I'm not seeing it in my own codiusd logs, I'm going to assume this is fixed and close
