### ISSUE TITLE
New announcement mailing list request

### ISSUE THREAD

**Issue by soliddash** [codius/codiusd#41]
Can I request a mailing list for announcements, for things like with moneyd-xrp rpm is updated, new version of codiusd is pushed and also when things like hyperd needs updating.

Thx,
Chris

**Comment by justmoon** [comment]
Good idea, I'll set something up.

**Comment by justmoon** [comment]
Created a new mailing list: https://www.stampready.net/list/index.php?list=z7t4lafHVoebKh5EwnvBiyIg

@njlie Can you add a signup form to the Codius website? This is the same provider as the Coil.com mailing list except different identifiers (these are public):

```
Public API: 40pQe9S3RtkZKbMiuOUs
List Key: z7t4lafHVoebKh5EwnvBiyIg
```

**Comment by soliddash** [comment]
Perfect thanks!
