### ISSUE TITLE
How to resolve exceeded money bandwidth errors?

### ISSUE THREAD

**Issue by theogravity** [codius/codiusd#43]
A few of us have the codius host env set up and are able to run the examples locally and get back a pod + url to it, which works.

However, when we try the example against an external host, the codius client log has `money bandwidth exceeded`, with several retries.

What client/server config is necessary to get around this? My wallet is funded with 120 xrp.

```

  ilp-plugin-btp processing btp packet {"type":1,"requestId":4098386379,"data":{"protocolData":[{"protocolName":"ilp","contentType":0,"data":{"type":"Buffer","data":[14,51,84,48,52,8,103,46,115,99,121,108,108,97,37,101,120,99,101,101,100,101,100,32,109,111,110,101,121,32,98,97,110,100,119,105,100,116,104,44,32,116,104,114,111,116,116,108,105,110,103,46,0]}}]}} +2s
  ilp-plugin-btp received BTP packet (TYPE_RESPONSE, RequestId: 4098386379): {"protocolData":[{"protocolName":"ilp","contentType":0,"data":{"type":"Buffer","data":[14,51,84,48,52,8,103,46,115,99,121,108,108,97,37,101,120,99,101,101,100,101,100,32,109,111,110,101,121,32,98,97,110,100,119,105,100,116,104,44,32,116,104,114,111,116,116,108,105,110,103,46,0]}}]} +0ms
  ilp-protocol-stream:Client:Connection packet 7 was rejected +95ms
  ilp-protocol-stream:Client:Stream:1 cancelled holdId: 7 for: 22821 +97ms
  ilp-protocol-stream:Client:Connection handling reject: {"code":"T04","triggeredBy":"g.scylla","message":"exceeded money bandwidth, throttling.","data":{"type":"Buffer","data":[]}} +0ms
  ilp-protocol-stream:Client:Connection got temporary error. waiting 3200 before trying again +0ms
```

We've been trying to figure it out in the gitter chat.

**Comment by sharafian** [comment]
This is due to an upstream connector being misconfigured to not have a maximum packet amount. I've reloaded scylla to have a maximum packet amount, so this error shouldn't be happening anymore. Can you try it again and let me know if it's fixed for you too?

@adrianhopebailie  @justmoon can you make sure that your connectors have max packet sizes of ~1000 drops too?

**Comment by theogravity** [comment]
Thanks for the response - I'll be able to test tonight and get back to you on the results.

**Comment by theogravity** [comment]
It worked! Thanks all.
