### ISSUE TITLE
capture and report codiusd.service configuration parsing issues 

### ISSUE THREAD

**Issue by mayoung6** [codius/codiusd#59]
In my codiusd.service configuration file, the "CODIUS_PUBLIC_URI" property value was missing an ending double-quote.  This caused my host to be discovered as "http://local.codius.org:3000" (default).  While the fix was clear, it took quite some time to see this as there were no errors or warnings.  Can the configuration be validated such that any potential issues may be, at least, flagged as warnings in log?

**Comment by andywong418** [comment]
As of pull request #39 "http://local.codius.org:3000" should not be discoverable as a peer but I agree that we should add a warning if there is no CODIUS_PUBLIC_URI set and CODIUS_DEV is not set.

**Comment by spearl** [comment]
We can't directly validate the configuration as this is interpreted by systemd not codiusd, but we can check the environment for missing or invalid values and we could also add logging to declare when we are taking a default value and not a provided one.
