### ISSUE TITLE
Request: Put back fullMem as a number instead of a bool

### ISSUE THREAD

**Issue by steffenmandrup** [codius/codiusd#71]
With 1.1.0 you made fullMem a bool and it is now not possible to see the memory allocation anymore.

I would like to request that the value is put back for general knowledge about RAM capacity throughout the network. If its to have a variable for an easy check if the host is available, then i suggest adding a "available" variable.

**Comment by adrianhopebailie** [comment]
There are some security implications of exposing this. i.e. If you wanted to attack the network you'd focus DoS attacks on machines with low available memory.

Any ideas on how to do this safely or theories as to why this is an overstated risk?

**Comment by steffenmandrup** [comment]
In general i think that if you wanted to DoS then you would use various methods to target individuals. Combined with this then usually DoS attacks have quite the power attached to them, which would make the memory or computing size of a server irrelevant anyway. The value itself is at this stage an important factor for a developer to choose where to host his stuff - as well as to showcase the network combined amount. An idea could be to put the value under the additional_host_info config - then it is the host itself who takes the risk, just like "runningContracts"
