### ISSUE TITLE
Any reason why project is standardising on hyperd that has now been merged?

### ISSUE THREAD

**Issue by natiki** [codius/codiusd#73]
Hi,

According to hyper.sh hyperd has now been subsumed by www.katacontainers.io. See  
https://twitter.com/hyper_sh/status/1006340953429323778.

Just curious about how this is going to affect Codius moving forward? Will we still be running HyperContainers or KataContainers?

**Comment by sharafian** [comment]
For now, there's no pressing reason to upgrade. If we start running into issues as a result of hyper's deprecation then we may non-breakingly upgrade codius's backend to use katacontainers instead

**Comment by natiki** [comment]
Appreciate the clarification.
