### ISSUE TITLE
Save DB on Pod Deletion

### ISSUE THREAD

**Issue by traviscrist** [codius/codiusd#81]
When a pod is deleted from we should immediately save it to the DB, currently its just stored in local memory so if the host is restarted before its saved then it will not be removed from the db. 

https://github.com/codius/codiusd/blob/master/src/services/PodDatabase.ts#L37

**Comment by spearl** [comment]
@traviscrist are you working on this?

**Comment by traviscrist** [comment]
@spearl not at this time, feel free to take the issue.
