### ISSUE TITLE
Don't update DB if pod fails to launch

### ISSUE THREAD

**Issue by njlie** [codius/codiusd#84]
If a manifest with a faulty image is uploaded, the DB is still updated and lists the associated hash with `running: true`.

**Comment by sharafian** [comment]
Maybe we should be checking all the images that Codiusd thinks are running and make sure that they're also running in hyperd. That would solve this issue and also any problem where the pod you uploaded died and codiusd thinks that it's still running

**Comment by traviscrist** [comment]
> Maybe we should be checking all the images that Codiusd thinks are running and make sure that they're also running in hyperd. 
It would also detect manually removed pods as well which would be good.
