### ISSUE TITLE
Feature Request: Codius startup self test

### ISSUE THREAD

**Issue by traviscrist** [codius/codiusd#93]
- [x] At startup codiusd should run a self test that uploads a contract to itself to test that codiusd, moneyd, and hyperd are all working correctly. 
- [x] Test should be run before peer discovery and responding to peer requests is enabled.
- [x] Test should retry itself x times before failure to ensure it passes if web sockets are configured.

**Comment by andywong418** [comment]
We could also check if web sockets are enabled in this contract, perhaps then adding whether this is turned on to the info endpoint.

**Comment by andywong418** [comment]
We could also check if web sockets are enabled in this contract, perhaps then adding whether this is turned on to the info endpoint. Though obviously a host can still 'fake' this fact.

**Comment by traviscrist** [comment]
Completed in #106, closing.

**Comment by traviscrist** [comment]
Reopening since failing at startup causes codiusd to just thrash when started using systemd instead of stopping startup.
